---
title: "Explore AQS monitor datasets"
author: Rachel Tao
output: github_document

---

```{r setup, include = FALSE}

library(tidyverse)
library(lubridate)
library(ggmap)
library(ggcorrplot)
library(gplots)
library(GGally)
library(knitr)
library(patchwork)
library(dygraphs)

knitr::opts_chunk$set(
	fig.asp = 0.6,
	fig.width = 6,
	out.width = "90%"
)
theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis")

#scale_colour_discrete = scale_colour_viridis_d
#scale_fill_discrete = scale_fill_viridis_d
```

```{r load data, message=FALSE, warning=FALSE, include=FALSE}

rename_pollutants = function(df){
  data = df %>% 
  rename(
    aluminum = aluminum_pm2_5_lc_88104, 
    arsenic = arsenic_pm2_5_lc_88103,
    barium = barium_pm2_5_lc_88107,
    bromine = bromine_pm2_5_lc_88109,
    cadmium = cadmium_pm2_5_lc_88110,
    calcium = calcium_pm2_5_lc_88111,
    chromium = chromium_pm2_5_lc_88112,
    copper = copper_pm2_5_lc_88114,
    iron = iron_pm2_5_lc_88126,
    lead = lead_pm2_5_lc_88128,
    magnesium = magnesium_pm2_5_lc_88140,
    manganese = manganese_pm2_5_lc_88132,
    nickel = nickel_pm2_5_lc_88136,
    selenium = selenium_pm2_5_lc_88154,
    silicon = silicon_pm2_5_lc_88165,
    sulfate = sulfate_pm2_5_lc_88403,
    sulfur = sulfur_pm2_5_lc_88169,
    titanium = titanium_pm2_5_lc_88161,
    nitrates = total_nitrate_pm2_5_lc_88306,
    vanadium = vanadium_pm2_5_lc_88164,
    zinc = zinc_pm2_5_lc_88167
    )
}

components_all <- 
  read_csv("./data/pm2.5_components_daily_nyc_3sites_averg.csv") %>% 
  rename_pollutants()

components_any <- 
  read_csv("./data/pm2.5_components_daily_nyc_any3_averg.csv")

components_124 <- 
  read_csv("./data/pm2.5_components_daily_nyc_site124.csv") %>% 
  rename_pollutants()

total_pm2.5 <- read_csv("./data/pm2.5_total_components_daily_nyc_avg.csv")

components_any_tot <- 
  components_any %>%
  rename_pollutants %>% 
  left_join(total_pm2.5, by = "date_local", copy = TRUE) %>%
  select(date_local:pm2.5_total)

```


```{r echo=FALSE, warning=FALSE}
components_any_tot %>% 
  select(-sulfur, -pm2.5_total) %>% 
  ggcorr(method = c("everything", "spearman"), limits = FALSE,
       label = TRUE, label_size = 2, label_alpha = 0.75, geom = "tile",
       hjust = 0.85, size = 3, color = "grey25", legend.size = 8, layout.exp = 3) + 
       ggtitle("Correlation Matrix: NYC Air Pollution Dataset \n (any available monitor)")
```

### Missingness over time

```{r echo=FALSE, message=FALSE}
time_any <-   
  components_any %>% 
  select(date_local) %>% 
  mutate(
    any_monitor = 1
  )

time_all <- 
  components_all %>% 
  select(date_local) %>% 
  mutate(
    all_monitors = 2
  )

time_queens <- 
  components_124 %>% 
  select(date_local) %>% 
  mutate(
    queens_monitor = 3
  )

time <- 
  left_join(time_any, time_all, by = "date_local") %>% 
  left_join(time_queens, by = "date_local")

time %>% 
  ggplot(aes(date_local, any_monitor, color = "darkgreen")) +
  geom_line() +
  geom_line(data = time, aes(y = queens_monitor, color = "blue")) +
  geom_line(data = time, aes(y = all_monitors, color = "red")) +
  theme(legend.position = "right",
        axis.title = element_blank(),
        axis.text.y = element_blank()) +
  scale_color_identity(name = "Dataset",
                       breaks = c("blue", "red", "darkgreen"),
                       labels = c("Queens monitor", "All monitors", "Any monitor"),
                       guide = "legend") +
  ylim(0, 4)

#this is not quite right - I need to start with a column that includes all dates 2000-2015 so we can see missingness in the 'any monitor' dataset.

```


PCA any

```{r echo=FALSE}

components_any <- 
  components_any %>% 
  rename_pollutants() %>% 
  select(-X1, -date_local, -sulfur)

pca_any <- 
  components_any %>%
  scale(center = FALSE, scale = apply(components_any, 2, sd, na.rm = TRUE)) %>% 
  prcomp()

summary(pca_any)

loadings_any <- 
  pca_any$rotation %>% 
  as_tibble() %>% 
  mutate(Chemicals = colnames(components_any)) %>% 
  select(Chemicals, PC1:PC6) %>% 
  gather(key = Component, value = Loadings, -Chemicals) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>%
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_point() +
  geom_segment(aes(yend=0, xend = Chemicals)) +
  facet_wrap(.~Component) + theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank()) +
  ggtitle("Any available monitor")

scores_pca <- pca_any$x

```

PCA all

```{r echo=FALSE}
components_all <- 
  components_all %>% 
  select(-date_local, -X1, -sulfur)

pca_all <- 
  components_all %>% 
  scale(center = FALSE, scale = apply(components_all, 2, sd, na.rm = TRUE)) %>% 
  prcomp()

summary(pca_all)

loadings_all <- 
  pca_all$rotation %>% 
  as_tibble() %>% 
  mutate(Chemicals = colnames(components_all)) %>% 
  select(Chemicals, PC1:PC6) %>% 
  gather(key = Component, value = Loadings, -Chemicals) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>%
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_point() +
  geom_segment(aes(yend=0, xend = Chemicals)) +
  facet_wrap(.~Component) + theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank()) +
  ggtitle("All Monitors")

scores_pca <- pca_all$x
```

PCA queens

```{r echo=FALSE}
components_124 <- 
  components_124 %>% 
  select(-date_local, -X1, -sulfur)

pca_124 <- 
  components_124 %>% 
  scale(center = FALSE, scale = apply(components_124, 2, sd, na.rm = TRUE)) %>% 
  prcomp()

summary(pca_all)

loadings_124 <-   
  pca_124$rotation %>% 
  as_tibble() %>% 
  mutate(Chemicals = colnames(components_124)) %>% 
  select(Chemicals, PC1:PC6) %>% 
  gather(key = Component, value = Loadings, -Chemicals) %>%
  mutate(Chemicals = fct_inorder(Chemicals)) %>%
  ggplot(aes(x = Chemicals, y = Loadings)) + geom_point() +
  geom_segment(aes(yend=0, xend = Chemicals)) +
  facet_wrap(.~Component) + theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1),
        legend.position = "bottom",
        strip.background = element_blank()) +
  ggtitle("Queens Monitor")

scores_pca <- pca_124$x
```

### Loadings

```{r echo=FALSE}
loadings_any
loadings_all
loadings_124
```

### Distribution

```{r echo=FALSE}
components_any <- 
  components_any %>% 
  mutate(
    dataset = "any_monitor"
  )

components_all <- 
  components_all %>% 
  mutate(
    dataset = "all_monitors"
  )

components_124 <- 
components_124 %>% 
  mutate(
    dataset = "queens_monitor"
  )

components <- 
  bind_rows(components_any, components_all, components_124) %>% 
  pivot_longer(aluminum:zinc,
    names_to = "pollutant",
    values_to  = "concentration"
  )

components95 <- 
  bind_rows(components_any, components_all, components_124) %>% 
  filter(
    aluminum < quantile(aluminum, 0.95),
    arsenic < quantile(arsenic, 0.95),
    barium < quantile(barium, 0.95),
    bromine < quantile(bromine, 0.95),
    cadmium < quantile(cadmium, 0.95),
    calcium < quantile(calcium, 0.95),
    chromium < quantile(chromium, 0.95),
    copper < quantile(copper, 0.95),
    iron < quantile(iron, 0.95),
    lead < quantile(lead, 0.95),
    magnesium < quantile(magnesium, 0.95),
    manganese < quantile(manganese, 0.95),
    nickel < quantile(nickel, 0.95),
    nitrates < quantile(nitrates, 0.95),
    selenium < quantile(selenium, 0.95),
    silicon < quantile(silicon, 0.95),
    sulfate < quantile(sulfate, 0.95),
    titanium < quantile(titanium, 0.95),
    vanadium < quantile(vanadium, 0.95),
    zinc < quantile(zinc, 0.95)
    ) %>% 
  pivot_longer(aluminum:zinc,
    names_to = "pollutant",
    values_to  = "concentration"
  )

components %>% 
  ggplot(aes(x = concentration, y = dataset, fill = dataset)) +
  geom_violin(alpha = 0.5, trim = FALSE) +
  facet_wrap(. ~pollutant, scales = "free") +
  theme(axis.title = element_blank()) +
  ggtitle("Violin Plots: Full distributions all 3 datasets") +
  theme(
    axis.text = element_text(size = 4),
    axis.title.y.left = element_text(size = 0))

components %>% 
  ggplot(aes(x = concentration, fill = dataset)) +
  geom_density(alpha = 0.5, trim = TRUE, position = "identity") +
  facet_wrap(. ~pollutant, scales = "free") +
  ggtitle("Density Plots: Full distributions all 3 datasets") +
  theme(
    axis.text = element_text(size = 4)) 

components95 %>% 
  ggplot(aes(x = concentration, fill = dataset)) +
  geom_density(alpha = 0.5, trim = TRUE, position = "identity") +
  facet_wrap(. ~pollutant, scales = "free") +
  ggtitle("Density Plots: Bottom 95th%ile all 3 datasets") +
  theme(
    axis.text = element_text(size = 4))


components95 %>% 
  filter(dataset != 'queens_monitor') %>% 
  ggplot(aes(x = concentration, fill = dataset)) +
  geom_density(alpha = 0.5, trim = TRUE) +
  facet_wrap(. ~pollutant, scales = "free") +
  ggtitle("Density Plots: All vs. Any, Bottom 95th%ile") +
  theme(
    axis.text = element_text(size = 4))


components95 %>% 
  ggplot(aes(x = concentration, fill = dataset)) +
  geom_histogram(alpha = 0.5, position = "identity", binwidth = 0.001) +
  facet_wrap(. ~pollutant, scales = "free") +
  ggtitle("Histograms bin = 0.001") +
  theme(
    axis.text = element_text(size = 4))


```


```{r echo=FALSE}
PCA_any <- pca_any$sdev^2/sum(pca_any$sdev^2) *100
PCA_all <- pca_all$sdev^2/sum(pca_all$sdev^2) *100
PCA_124 <- pca_124$sdev^2/sum(pca_124$sdev^2) *100
round(cbind(Component = 1:20, PCA_any, PCA_all, PCA_124), 4) %>% kable()
```

geometry column in R with coordinates